version: '2'

services:
  nginx:
    image: nginx:1.11-alpine
    volumes:
      - ".:/var/www/html:ro"
      - "./nginx:/etc/nginx/conf.d:ro"
    depends_on:
      - php
    ports:
      - "8080:80"

  php:
    image: greut/laravel:latest
    build: .
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      #- DB_CONNECTION=pgsql
      #- DB_HOST=postgres
      - DB_DATABASE=forge
      - DB_USERNAME=forge
      - DB_PASSWORD=forge
    depends_on:
      # Pick either MySQL or Postgresql.
      - mysql
      #- postgres
      - redis
      - mail
    volumes:
      - ".:/var/www/html"

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data

  #postgres:
  #  image: postgres:9.6
  #  environment:
  #    - POSTGRES_PGDATA=/var/lib/postgresql/data/pgdata
  #    - POSTGRES_DB=forge
  #    - POSTGRES_USER=forge
  #    - POSTGRES_PASSWORD=forge
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - postgres:/var/lib/postgresql/data

  mysql:
    image: mariadb:10.1
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=forge
      - MYSQL_USER=forge
      - MYSQL_PASSWORD=forge
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  mail:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

volumes:
  mysql:
  #postgres:
  redis:
